### PR TITLE
RDKCOM-3645: ONEM-27170 Fix compilation with gssdp-1.2.3 (#4)

### PR DESCRIPTION
**Pull request by poojah58**
- Fixes compilation with gssdp-1.2.3[1]
 - Fix compilation error: too many arguments to function 'gssdp_client_new'

[1] http://errors.onemw.net/Errors/Details/129057/

(cherry picked from commit 1dc43ed7f24214a88a773e272e29dbb39f41be9f)

RDKCOM-3645: ONEMPERS-640 fix strdup memleak in xdial (#11)

strdup'ed memory was never released (as confirmed
with valgrind)

(cherry picked from commit 826f7df165ff97c7b9612660e0b655bb01056e69)

RDKCOM-3645: ONEM-27757: other warnings and issues (#7)

compilation warnings removed
.gitignore updated

Second compilation failed on builds with gssdp-1.0 Adressed warnings:
/home/mikolaj.staworzynski/projects/eos2008c_20220922/onemw/onemw-src/onemw-xdialserver/server/plat/rtcache.cpp:47:95: warning: format '%s' expects argument of type 'char*', but argument 2 has type 'std::__cxx11::string* {aka std::__cxx11::basic_string<char>*}' [-Wformat=] /home/mikolaj.staworzynski/projects/eos2008c_20220922/onemw/onemw-src/onemw-xdialserver/server/plat/rtcache.cpp:52:95: warning: format '%s' expects argument of type 'char*', but argument 2 has type 'std::__cxx11::string* {aka std::__cxx11::basic_string<char>*}' [-Wformat=] /home/mikolaj.staworzynski/projects/eos2008c_20220922/onemw/onemw-src/onemw-xdialserver/server/gdial-ssdp.c:162:3: warning: format not a string literal, argument types not checked [-Wformat-nonliteral] /home/mikolaj.staworzynski/projects/eos2008c_20220922/onemw/onemw-src/onemw-xdialserver/server/gdial-ssdp.c:163:3: warning: format not a string literal, argument types not checked [-Wformat-nonliteral] /home/mikolaj.staworzynski/projects/eos2008c_20220922/onemw/onemw-src/onemw-xdialserver/server/main.c:197:3: warning: implicit declaration of function 'gdial_plat_register_friendlyname_cb' [-Wimplicit-function-declaration] /home/mikolaj.staworzynski/projects/eos2008c_20220922/onemw/onemw-src/onemw-xdialserver/server/main.c:199:3: warning: not enough variable arguments to fit a sentinel [-Wformat=] /home/mikolaj.staworzynski/projects/eos2008c_20220922/onemw/onemw-src/onemw-xdialserver/server/main.c:200:3: warning: not enough variable arguments to fit a sentinel [-Wformat=] /home/mikolaj.staworzynski/projects/eos2008c_20220922/onemw/onemw-src/onemw-xdialserver/server/main.c:201:3: warning: not enough variable arguments to fit a sentinel [-Wformat=] /home/mikolaj.staworzynski/projects/eos2008c_20220922/onemw/onemw-src/onemw-xdialserver/server/main.c:262:13: warning: passing argument 1 of 'free' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]

TODO: check - Conflicts:
   server/main.c
(cherry picked from commit 2c9a8eb7a70fbed816ab37209c555798ce082f8a)

RDKCOM-3645: OMWAPPI-1142 fix xdial warning (#19)

This removes most of xdial warnings; remaining ones are either caused by libsoup/glib version discrepancies or strange redefinitions of 'EXTERNAL' in couple
wpeframework files

(cherry picked from commit aebaf28e852522ef23e9b69b4c3fc09868d79089)

Signed-off-by: tomasz-karczewski-red <tomasz.karczewski@redembedded.com>

### CODE REVIEW

**Comment by pradeeptakdas** [comment]
Hi @tomasz-karczewski-red 
Can you please address the review comments added by Amit?

**Review by apatel859 — APPROVED** [review]
